compile:
	ec typeobjects.m hash.m peer.m server.m nopester.m
run:
	emx typeobjects.x hash.x peer.x server.x nopester.x
setup:
	emx -R$(host)
setupp:
	emx32 -U -R$(host)
runp:
	emx32 -U -R$(host) typeobjects.x hash.x peer.x server.x nopester.x
